name: my_app
description: A new Flutter project.
publish_to: 'none' # Remove this if you're publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  record: ^6.1.1
  record_windows: ^1.0.7
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.3.0
  image_picker: ^1.0.7
  path: ^1.8.3
  supabase_flutter: ^1.10.0
  supabase: ^1.11.11
  google_fonts: ^6.1.0
  logger: ^2.0.2
  http: ^1.5.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  geolocator: ^10.0.0
  path_provider: ^2.0.9
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1 
  tflite_flutter: ^0.10.4
  csv: ^6.0.0
  provider: ^6.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/yamnet.tflite
    - assets/models/yamnet_class_map.csv
